"""Calendario 8-21 novembre 2026 -> data/calendar_2026-11.json (stessa struttura di calendar_2026-10.json)."""
import json,os
R=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SVC=['Spedizione gratuita in Italia, consegna in 24/48 ore.','Spedizione gratuita in Italia con BRT, consegna in 24/48 ore.','In Italia spediamo gratis: consegna in 24/48 ore.','Spedizione gratuita, reso entro 14 giorni.']
DM='Scrivici targa, modello e anno in DM: verifichiamo noi la specifica giusta.'
CL='autoevostore.it (link in bio)'
P=[] 
def post(key,dt,media,cap,alts,typ='POST',thumb=None):
    P.append(dict(key=key,kind='reel' if typ=='REEL' else 'post',dt=dt,media=media,caption=cap,alts=alts,type=typ,thumb=thumb))
def story(n,dt,alt): P.append(dict(key='st'+n,kind='story',dt=dt,media=['2026-11/st%s.jpg'%n],caption='',alts=[alt],type='STORY'))
J=lambda *a:'\n\n'.join(a)
post('dom08','2026-11-08T18:30',['2026-11/dom08.jpg'],J("Quando scegli l'olio, cosa guardi per prima?\n\nA) La viscosità (5W-30, 5W-40...)\nB) Il marchio\nC) L'omologazione del costruttore\nD) Non lo so: mi affido a chi lo sa","Rispondi nei commenti. Se sei tra i D: scrivici targa, modello e anno in DM, verifichiamo noi la specifica giusta.",CL,"#oliomotore #omologazioni #autoevostore #lubrificanti #manutenzioneauto"),["Domanda della domenica: cosa guardi per prima quando scegli l'olio? Viscosità, marchio, omologazione o non lo so"])
post('prod09','2026-11-09T18:30',['2026-11/prod09_forward.jpg'],J("Selenia WR Forward 0W-30.\nOlio motore sintetico · ACEA C2 · FIAT 955535-DS1/DH1.","Controlla il libretto: se la tua auto richiede questa specifica FIAT, questo è l'olio da cercare. Dubbi? Scrivici targa e modello in DM: verifichiamo noi la specifica giusta.",SVC[1],CL,"#selenia #mopar #fiat #0w30 #oliomotore #autoevostore"),["Flacone Selenia WR Forward 0W-30 da 1 litro: ACEA C2, FIAT 955535-DS1/DH1"])
post('car10','2026-11-10T18:30',['2026-11/car10_%d.jpg'%i for i in range(1,6)],J("Olio cambio e differenziale: non è tutto olio motore.","Castrol Transmax Axle EPX 80W-90: API GL-5, ZF TE-ML.\nMANNOL Ultra Gear Oil 8118 75W-90: semisintetico, API GL-5, SAE J2360.","Attenzione: la classe GL-5 non va bene per tutti i cambi manuali sincronizzati, alcuni costruttori richiedono solo GL-4. Il libretto decide.",DM+" Salva il post per il prossimo intervento.",SVC[0]+"\n"+CL,"#oliocambio #differenziale #gl5 #castrol #mannol #autoevostore"),["Castrol Transmax Axle EPX 80W-90 e MANNOL Ultra Gear 8118 75W-90: non è tutto olio motore","Castrol Transmax Axle EPX 80W-90: API GL-5, ZF TE-ML","MANNOL Ultra Gear Oil 8118 75W-90: semisintetico, API GL-5, SAE J2360","Attenzione: la classe GL-5 non è adatta a tutti i cambi manuali sincronizzati","Scrivici targa, modello e anno in DM: verifichiamo noi la specifica giusta"])
post('car11','2026-11-11T18:30',['2026-11/car11_%d.jpg'%i for i in range(1,6)],J("Tre 0W-30. Tre specifiche diverse.","Castrol EDGE 0W-30 LL: ACEA C3, VW 504.00/507.00.\nCastrol MAGNATEC 0W-30 D: ACEA C2, Ford WSS-M2C950-A.\nSelenia WR Forward 0W-30: ACEA C2, FIAT 955535-DS1/DH1.","Cambia l'omologazione, non il grado. Quale serve alla tua auto lo dice il libretto.",DM+" Salva il post.",SVC[2]+"\n"+CL,"#0w30 #oliomotore #omologazioni #castrol #selenia #autoevostore"),["Tre flaconi 0W-30: Castrol EDGE LL, Castrol MAGNATEC D e Selenia WR Forward, tre specifiche diverse","Castrol EDGE 0W-30 LL: ACEA C3, VW 504.00/507.00","Castrol MAGNATEC 0W-30 D: ACEA C2, Ford WSS-M2C950-A","Selenia WR Forward 0W-30: ACEA C2, FIAT 955535-DS1/DH1","Quale serve alla tua auto? Scrivici targa, modello e anno in DM"])
post('prod12','2026-11-12T18:30',['2026-11/prod12_magnatec.jpg'],J("Castrol MAGNATEC 5W-30 A5.\nOlio motore · ACEA A5/B5 · Ford WSS-M2C913.","Controlla il libretto: se la tua auto richiede questa specifica Ford, questo è l'olio da cercare. Dubbi? Scrivici targa e modello in DM e verifichiamo noi.",SVC[0],CL,"#castrol #magnatec #ford #5w30 #oliomotore #autoevostore"),["Flacone Castrol MAGNATEC 5W-30 A5 da 1 litro: ACEA A5/B5, Ford WSS-M2C913"])
post('reel13','2026-11-13T18:30',['media/reels/reel_errori.mp4'],J("Tre errori che fanno comprare l'olio sbagliato.","1. Guardare solo la viscosità: due 5W-40 possono avere omologazioni diverse.\n2. Scegliere per marchio: conta la specifica richiesta dal costruttore.\n3. Non aprire il libretto: la risposta è lì.",DM+" Salva il reel per il prossimo tagliando.",SVC[0]+"\n"+CL,"#reel #oliomotore #omologazioni #autoevostore #lubrificanti #manutenzioneauto"),["Reel: tre errori che fanno comprare l'olio sbagliato"],'REEL','media/reels/reel_errori.jpg')
post('sab14','2026-11-14T12:00',['2026-11/sab14.jpg'],J("Tre dati, una specifica.","Per scegliere l'olio giusto ci servono targa, modello e anno. Scrivici in DM: con questi dati controlliamo insieme a te la specifica sul libretto. Non serve la foto del libretto intero.","Assistenza dal lunedì al venerdì, 9:00-18:00. Scrivici anche nel weekend: ti rispondiamo dal lunedì.",CL,"#assistenza #oliomotore #autoevostore #lubrificanti #manutenzioneauto"),["Tre dati, una specifica: targa, modello e anno"])
post('dom15','2026-11-15T18:30',['2026-11/dom15.jpg'],J("Vero o falso?\n\n\"Se la viscosità è giusta, va bene qualsiasi olio.\"","Rispondi nei commenti con V o F. La risposta domani nelle storie.","Vuoi la specifica giusta per la tua auto? Scrivici targa, modello e anno in DM.",CL,"#veroofalso #oliomotore #omologazioni #autoevostore #lubrificanti"),["Vero o falso: se la viscosità è giusta, va bene qualsiasi olio"])
post('prod16','2026-11-16T18:30',['2026-11/prod16_diesel.jpg'],J("Selenia WR 5W-40 Diesel.\nOlio motore sintetico · ACEA A3/B4 · API SN/CF · FIAT 9.55535-N2/N3.","Controlla il libretto: se la tua auto richiede queste specifiche FIAT, questo è l'olio da cercare. Dubbi? Scrivici targa e modello in DM: verifichiamo noi la specifica giusta.",SVC[1],CL,"#selenia #diesel #5w40 #fiat #oliomotore #autoevostore"),["Flacone Selenia WR 5W-40 Diesel da 1 litro: ACEA A3/B4, API SN/CF, FIAT 9.55535-N2/N3"])
post('car17','2026-11-17T18:30',['2026-11/car17_%d.jpg'%i for i in range(1,7)],J("Le cinque domande che ci fanno di più.","1) Spedizione in Italia: gratuita, consegna in 24/48 ore con BRT.\n2) Europa: 3-7 giorni lavorativi, spedizione tracciata, costo calcolato al checkout. Escluse Cipro e Malta.\n3) Reso: entro 14 giorni.\n4) Assistenza: dal lunedì al venerdì, 9:00-18:00.\n5) Come scegliamo l'olio: targa, modello e anno in DM, verifichiamo noi la specifica giusta.","Salva il post: ti serve quando ordini.",CL,"#faq #oliomotore #autoevostore #spedizionegratuita #lubrificanti"),["Le cinque domande che ci fanno di più","Spedizione in Italia gratuita, 24/48 ore con BRT","Spedizione in Europa in 3-7 giorni lavorativi, escluse Cipro e Malta","Reso entro 14 giorni","Assistenza lunedì-venerdì 9:00-18:00","Come scegliamo l'olio: targa, modello e anno in DM"])
post('reel18','2026-11-18T18:30',['media/reels/reel_uso.mp4'],J("Non solo olio motore auto.","Castrol Power 1 Ultimate 2T per la moto, MANNOL 7207 Outboard Marine 2T per i motori marini, Castrol Transmax Axle EPX per il differenziale, MANNOL ATF Dexron III per cambi automatici e servosterzi.","Scegli per uso e per specifica: il libretto o il manuale del mezzo dicono quale serve. Scrivici targa o modello in DM: verifichiamo noi.",SVC[2]+"\n"+CL,"#reel #oliomoto #2tempi #atf #oliocambio #autoevostore #lubrificanti"),["Reel: non solo olio motore auto, moto, motori marini, differenziale e cambio automatico"],'REEL','media/reels/reel_uso.jpg')
post('prod19','2026-11-19T18:30',['2026-11/prod19_mannol.jpg'],J("MANNOL Longlife 504/507 5W-30.\nOlio motore · ACEA C3 · VW 504.00/507.00 · Porsche C30.","Controlla il libretto: se la tua auto richiede una di queste specifiche, questo è l'olio da cercare. Dubbi? Scrivici targa e modello in DM e verifichiamo noi.",SVC[0],CL,"#mannol #longlife #5w30 #oliomotore #autoevostore #lubrificanti"),["Flacone MANNOL Longlife 504/507 5W-30 da 1 litro: ACEA C3, VW 504.00/507.00, Porsche C30"])
post('prod20','2026-11-20T18:30',['2026-11/prod20_pure.jpg'],J("Petronas Selenia WR Pure Energy 5W-30.\nOlio motore · ACEA C2 · FIAT / Mopar.","Controlla il libretto: se la tua auto richiede una specifica FIAT o Mopar, verifica che coincida con quella indicata. Dubbi? Scrivici targa e modello in DM: verifichiamo noi la specifica giusta.",SVC[0],CL,"#selenia #petronas #mopar #5w30 #oliomotore #autoevostore"),["Flacone Petronas Selenia WR Pure Energy 5W-30 da 1 litro: ACEA C2, FIAT / Mopar"])
post('sab21','2026-11-21T12:00',['2026-11/sab21.jpg'],J("Non ricordi cosa significano ACEA, API e OEM?","Sul nostro sito c'è la guida alle sigle, spiegate in modo semplice. Cerca \"Guida alle sigle\" su autoevostore.it, oppure scrivici targa, modello e anno in DM: verifichiamo noi la specifica giusta.",CL,"#acea #api #omologazioni #oliomotore #autoevostore #lubrificanti"),["Non ricordi cosa significa ACEA? Sul sito c'è la guida alle sigle"])
ST=[('08',"Lo sapevi? MB 229.51 e 229.52 sono omologazioni Mercedes-Benz"),('09',"Spedizione gratuita in Italia in 24/48 ore con BRT"),('10',"Lo sapevi? VW 504.00 e 507.00 sono norme Volkswagen"),('11',"Castrol: olio motore, cambio e differenziale"),('12',"Reso entro 14 giorni"),('13',"Lo sapevi? BMW Longlife-04 è un'omologazione BMW"),('14',"Scrivici anche il sabato: ti rispondiamo dal lunedì"),('15',"Hai il libretto a portata di mano?"),('16',"Risposta: falso, la viscosità non basta"),('17',"Spediamo anche in Europa in 3-7 giorni lavorativi"),('18',"Selenia: specifiche FIAT e Mopar"),('19',"Lo sapevi? FIAT 9.55535 è una famiglia di specifiche"),('20',"Assistenza lunedì-venerdì 9:00-18:00"),('21',"Sul sito c'è la guida alle sigle")]
for n,a in ST: story(n,'2026-11-%sT12:30'%n,a)
json.dump(P,open(R+'/data/calendar_2026-11.json','w'),ensure_ascii=False,indent=1)
print(len(P))
